name: fvm
description: A CLI to manage Flutter SDK versions
version: 1.0.0
repository: https://github.com/georges-ph/fvm

environment:
  sdk: ^3.1.4

dependencies:
  archive: ^3.4.6
  args: ^2.4.2
  console_bars: ^1.2.0
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
